name: punctuation_letter_digit

# `train` or `infer`, will be override by cmd args
mode: 'train'

# restore training from latest checkpoint
restore: true

# checkpoint directory
ckpt: ./ckpts/punctuation_letter_digit

# tensorboard log directory
tb_dir: ./tb/punctuation_letter_digit

# charmap path
charmap_path: label_maps/punctuation_letter_digit.json
charmap_exist: true

infer_output_path: ./infer.txt

dir_train: /usr/local/src/data/pld/train
dir_val: /usr/local/src/data/pld/val
dir_infer:

# [optional] size of dataset
train_size: -1
val_size: -1

# Which gpu for running. Running on cpu if `-1`
gpu: 0


# input image size
input_width: 64
input_height: 64

# batch size, number of samples in one batch
batch_size: 128

# number of classes
num_class: 90

# number of epochs
num_epochs: 100

# save model to checkpoint every these steps
save_interval: 256

# do validation every these steps
val_interval: 64
