name: single_char_3991

# `train` or `infer`, will be override by cmd args
mode: 'train'

# restore training from latest checkpoint
restore: false

# checkpoint directory
ckpt: ./ckpts/all_3991_0415

# tensorboard log directory
tb_dir: ./tb/all_3991_0415

# charmap path
charmap_path: ./label_maps/all_3991_0415.json
charmap_exist: false

infer_output_path: ./infer.txt

dir_train: /usr/local/src/data/stage3/all_3991/train
dir_val: /usr/local/src/data/stage3/all_3991/val
dir_infer: /usr/local/src/data/sc/hight_error

# [optional] size of dataset
train_size: 5582000
val_size: 549100

# Which gpu for running. Running on cpu if `-1`
gpu: 0


# input image size
input_width: 64
input_height: 64

# batch size, number of samples in one batch
batch_size: 128

# number of classes
num_class: 3991

# number of epochs
num_epochs: 100

# save model to checkpoint every these steps
save_interval: 256

# do validation every these steps
val_interval: 256
